<?php

/**
 * Quick and dirty file fetcher, to be able to fetch files generated by the Horaro Text File plugin over networks.
 */

$opts = "c:";
$longopts = [
    "config:"
];

$options = getopt($opts, $longopts);
$configFile = $options['c'] ?? $options['config'] ?? null;

if (empty($configFile)) {
    die("Missing config.\n");
}

$config = json_decode(file_get_contents($configFile), true);

if(empty($config)) {
    die("Invalid config.\n");
}

$previousContents = null;

while (true) {
    $contents = file_get_contents($config['input']);

    if($contents != $previousContents) {
        echo "Updating target files...\n";
        $previousContents = $contents;
        
        $contents = explode($config['split'], $contents);

        foreach($config['output'] as $output) {
            $outputContents = $output['content'];

            foreach($contents as $k => $part) {
                $outputContents = str_replace("$". $k, $part, $outputContents);
            }
            
            file_put_contents($output['file'], $outputContents);
        }
    }

    sleep($config['time']);
}